[features]
seeds = false
skip-lint = false

[programs.localnet]
swap = "EdeRcNsVGU1s1NXZZo8FhLD8iePxvoUCdbvwVGnj778f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/khangtd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
