[features]
seeds = false
skip-lint = false

[programs.localnet]
pocket = "G23zULdpfEmPs9pNBJnJ67kpRJjt9g442miPu1QX85tK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/khangtd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
